### ISSUE TITLE
Describe only failed matchers in AllOf

### ISSUE THREAD

**Issue by corbym** [corbym/gocrest#3]
AllOf reports all matcher's descriptions when it fails. 

Given a number of matchers, when less than all of them fail, we should only report the description of the failing matchers.

**Comment by jpolack** [comment]
Would be a nice feature, because if I understand right the description has to be changed based on the childMatchers' `.Matches` result.

Enabling this would make possible to write better descriptions/actuals in general

**Comment by corbym** [comment]
not sure what I was thinking here, cause it makes no sense for anyOf to fail matching less than all - its criteria is to match ANY of the matchers and pass. 
I must have meant AllOf..
